"""
ArangoDB vs Qdrant — RAG Retrieval Benchmark
=============================================
Uses the Cohere/beir-embed-english-v3 (FIQA subset) dataset with real
financial domain text, pre-computed 1024d Cohere v3 embeddings, and
human-annotated relevance judgments (qrels).

Benchmarks: indexing time, query duration (p50/p95/p99), throughput (QPS),
recall@k (vs qrels ground truth), and filtered search.

Both databases are used as pure retrieval engines (no LLM generation).

The dataset is ingested once per database using a fill-to-capacity approach:
documents are upserted in batches while monitoring container memory via Docker
stats, stopping when ~92% of the container memory limit is reached. Query
measurements are repeated across multiple runs for statistical robustness.

METHODOLOGY NOTES:
- ArangoDB uses an IVF (inverted-file) vector index; Qdrant uses HNSW (graph-based).
  These are fundamentally different algorithms with different recall/duration/memory
  trade-offs. Results reflect each engine's default/recommended ANN strategy.
- Each database is queried via its best available protocol: ArangoDB over
  HTTP/REST (its only query protocol) and Qdrant over gRPC (its fastest).
  This reflects the best real-world performance each engine can deliver.
- Throughput is measured with per-thread connections for both databases to
  avoid connection contention bias.
- Filtered search uses each engine's recommended filter optimization:
  ArangoDB uses storedValues on the vector index, Qdrant uses a payload index.
- Memory is measured from each engine's actual reported stats (ArangoDB
  collection figures API, Qdrant telemetry API).
- Each measurement (duration, throughput, recall) is repeated across multiple runs
  and reported as mean +/- stddev for statistical robustness.
- Both containers are memory-capped at 4 GB to test behavior under memory pressure.
  When dataset size exceeds the natural corpus (~57K), synthetic documents are
  generated by cloning existing docs with small Gaussian noise on embeddings.
"""

import json
import argparse
from pathlib import Path
from dataclasses import asdict

import numpy as np
from tabulate import tabulate

from config import NUM_QUERIES, NUM_RUNS, HF_SUBSET, TARGET_DOC_COUNT, NPROBE_SWEEP, EF_SWEEP
from dataset import load_beir_dataset
from docker import start_container, stop_container
from measure import BenchmarkResult, RecallDurationPoint
from arango_bench import run_benchmark_arango
from qdrant_bench import run_benchmark_qdrant
from plotting import plot_results
from checkpoint import load_checkpoint, save_checkpoint, db_is_complete


def _fmt(mean: float, std: float, fmt: str = ".1f") -> str:
    """Format a value as 'mean +/- std' or just 'mean' if std is negligible."""
    if std > 0.005:
        return f"{mean:{fmt}}\u00b1{std:{fmt}}"
    return f"{mean:{fmt}}"


def print_summary(all_results: list[BenchmarkResult]):
    print(f"\n  NOTE: ArangoDB uses IVF index (HTTP/REST); Qdrant uses HNSW index (gRPC).")
    print(f"  Each DB uses its best available query protocol. Values are mean\u00b1stddev across {all_results[0].num_runs} runs.\n")
    rows = []
    for r in all_results:
        rows.append([
            r.db_name,
            f"{r.dataset_size:,}",
            f"{r.index_time_s:.2f}",
            _fmt(r.duration_p50_ms, r.duration_p50_std),
            _fmt(r.duration_p95_ms, r.duration_p95_std),
            _fmt(r.duration_p99_ms, r.duration_p99_std),
            _fmt(r.throughput_qps, r.throughput_qps_std),
            _fmt(r.recall_at_k.get(10, 0), r.recall_at_k_std.get(10, 0), fmt=".4f"),
            _fmt(r.filtered_duration_p50_ms, r.filtered_duration_p50_std),
            f"{r.memory_mb:.1f}",
        ])
    headers = ["DB", "N", "Index(s)", "p50(ms)", "p95(ms)", "p99(ms)", "QPS", "R@10", "Filt p50(ms)", "Mem(MB)"]
    print(tabulate(rows, headers=headers, tablefmt="github"))


def main():
    parser = argparse.ArgumentParser(description="ArangoDB vs Qdrant RAG Retrieval Benchmark (BEIR/FIQA)")
    parser.add_argument("--queries", type=int, default=NUM_QUERIES,
                        help="Number of queries per benchmark run")
    parser.add_argument("--out", type=str, default="results",
                        help="Output directory for charts and JSON")
    parser.add_argument("--only", choices=["arango", "qdrant"], default=None,
                        help="Run only one database benchmark")
    parser.add_argument("--subset", type=str, default=HF_SUBSET,
                        help="BEIR subset to use (default: fiqa)")
    parser.add_argument("--runs", type=int, default=NUM_RUNS,
                        help="Number of measurement runs per config (default: 3)")
    parser.add_argument("--fresh", action="store_true",
                        help="Discard previous checkpoint and start fresh")
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Load or reset checkpoint
    if args.fresh:
        import shutil
        if out_dir.exists():
            shutil.rmtree(out_dir)
            out_dir.mkdir(parents=True, exist_ok=True)
        ckpt = {}
        print("  Starting fresh (previous results cleared).")
    else:
        ckpt = load_checkpoint(out_dir)
        if ckpt:
            print("  Found existing checkpoint — will resume where we left off.")
            print(f"    Use --fresh to discard and start over.")

    print(f"\n  Fixed dataset size: {TARGET_DOC_COUNT:,} documents per database")
    print(f"  Containers are managed automatically (start before benchmark, stop after)")

    # Determine what's already complete
    arango_pareto_count = len([v for v in NPROBE_SWEEP if v <= max(1, int(TARGET_DOC_COUNT ** 0.5))])
    qdrant_pareto_count = len(EF_SWEEP)
    arango_done = db_is_complete(ckpt, "arango", args.runs, arango_pareto_count)
    qdrant_done = db_is_complete(ckpt, "qdrant", args.runs, qdrant_pareto_count)

    if arango_done and args.only != "qdrant":
        print("  ArangoDB benchmark already complete (skipping).")
    if qdrant_done and args.only != "arango":
        print("  Qdrant benchmark already complete (skipping).")

    def make_save_fn():
        """Returns a function that saves the current checkpoint state."""
        def _save():
            save_checkpoint(out_dir, ckpt)
        return _save

    # Load dataset (needed unless both are done)
    need_arango = args.only != "qdrant" and not arango_done
    need_qdrant = args.only != "arango" and not qdrant_done

    if need_arango or need_qdrant:
        print(f"\n{'#'*60}")
        print(f"  Loading BEIR dataset: {args.subset}")
        print(f"{'#'*60}")
        corpus, queries, qrels = load_beir_dataset(args.subset)

        all_doc_ids = set(corpus.keys())
        usable_qids = []
        filtered_qrels = {}
        for qid, rels in qrels.items():
            relevant_in_corpus = {did: s for did, s in rels.items() if did in all_doc_ids and s > 0}
            if relevant_in_corpus:
                usable_qids.append(qid)
                filtered_qrels[qid] = relevant_in_corpus

        rng = np.random.default_rng(42)
        num_queries = args.queries
        if len(usable_qids) > num_queries:
            chosen_qids = rng.choice(usable_qids, size=num_queries, replace=False).tolist()
        else:
            chosen_qids = usable_qids
            if len(chosen_qids) < num_queries:
                print(f"  Warning: only {len(chosen_qids)} queries have relevant docs")

        query_vecs = np.array([queries[qid]["embedding"] for qid in chosen_qids], dtype=np.float32)
        print(f"  Prepared {len(chosen_qids)} queries with relevant docs")

    all_results: list[BenchmarkResult] = []
    all_pareto: list[RecallDurationPoint] = []

    if args.only != "qdrant":
        if arango_done:
            # Reconstruct result from checkpoint
            result, pareto = _rebuild_from_checkpoint(ckpt["arango"], "ArangoDB", "nProbe", args.runs)
            all_results.append(result)
            all_pareto.extend(pareto)
        else:
            ckpt.setdefault("arango", {})
            has_ingest = bool(ckpt["arango"].get("ingest"))
            start_container("arangodb", preserve_volumes=has_ingest)
            try:
                result, pareto = run_benchmark_arango(
                    corpus, query_vecs, chosen_qids, filtered_qrels,
                    num_runs=args.runs, ckpt_db=ckpt["arango"], save_fn=make_save_fn(),
                )
                all_results.append(result)
                all_pareto.extend(pareto)
            finally:
                stop_container("arangodb")

    if args.only != "arango":
        if qdrant_done:
            result, pareto = _rebuild_from_checkpoint(ckpt["qdrant"], "Qdrant", "ef", args.runs)
            all_results.append(result)
            all_pareto.extend(pareto)
        else:
            ckpt.setdefault("qdrant", {})
            has_ingest = bool(ckpt["qdrant"].get("ingest"))
            start_container("qdrant", preserve_volumes=has_ingest)
            try:
                result, pareto = run_benchmark_qdrant(
                    corpus, query_vecs, chosen_qids, filtered_qrels,
                    num_runs=args.runs, ckpt_db=ckpt["qdrant"], save_fn=make_save_fn(),
                )
                all_results.append(result)
                all_pareto.extend(pareto)
            finally:
                stop_container("qdrant")

    if all_results:
        print_summary(all_results)

    raw = [asdict(r) for r in all_results]
    pareto_raw = [asdict(p) for p in all_pareto]
    with open(out_dir / "results.json", "w") as f:
        json.dump({"benchmarks": raw, "pareto_curves": pareto_raw}, f, indent=2)
    print(f"\n  Raw results saved to {out_dir}/results.json")

    if len(all_results) >= 2:
        plot_results(all_results, out_dir, pareto_points=all_pareto)

    print("\n  Done!\n")


def _rebuild_from_checkpoint(
    db_ckpt: dict, db_name: str, param_name: str, num_runs: int,
) -> tuple[BenchmarkResult, list[RecallDurationPoint]]:
    """Reconstruct BenchmarkResult and pareto points from checkpoint data."""
    import statistics as stats
    from config import TOP_K_VALUES

    ingest = db_ckpt["ingest"]
    runs = db_ckpt["runs"]

    all_p50 = [r["p50"] for r in runs]
    all_p95 = [r["p95"] for r in runs]
    all_p99 = [r["p99"] for r in runs]
    all_qps = [r["qps"] for r in runs]
    all_fp50 = [r["fp50"] for r in runs]
    all_fp95 = [r["fp95"] for r in runs]
    all_recall = {k: [] for k in TOP_K_VALUES}
    for r in runs:
        for k in TOP_K_VALUES:
            all_recall[k].append(r["recall"][str(k)])

    result = BenchmarkResult(
        db_name=db_name,
        dataset_size=ingest["dataset_size"],
        index_time_s=ingest["index_time_s"],
        duration_p50_ms=stats.mean(all_p50),
        duration_p50_std=stats.stdev(all_p50) if len(all_p50) > 1 else 0.0,
        duration_p95_ms=stats.mean(all_p95),
        duration_p95_std=stats.stdev(all_p95) if len(all_p95) > 1 else 0.0,
        duration_p99_ms=stats.mean(all_p99),
        duration_p99_std=stats.stdev(all_p99) if len(all_p99) > 1 else 0.0,
        throughput_qps=stats.mean(all_qps),
        throughput_qps_std=stats.stdev(all_qps) if len(all_qps) > 1 else 0.0,
        recall_at_k={k: stats.mean(v) for k, v in all_recall.items()},
        recall_at_k_std={k: (stats.stdev(v) if len(v) > 1 else 0.0) for k, v in all_recall.items()},
        filtered_duration_p50_ms=stats.mean(all_fp50),
        filtered_duration_p50_std=stats.stdev(all_fp50) if len(all_fp50) > 1 else 0.0,
        filtered_duration_p95_ms=stats.mean(all_fp95),
        filtered_duration_p95_std=stats.stdev(all_fp95) if len(all_fp95) > 1 else 0.0,
        memory_mb=ingest["memory_mb"],
        num_runs=num_runs,
    )

    pareto = [
        RecallDurationPoint(
            db_name=db_name, dataset_size=ingest["dataset_size"],
            param_name=param_name, param_value=p["param_value"],
            recall_at_10=p["recall_at_10"], duration_p50_ms=p["p50"], duration_p95_ms=p["p95"],
        )
        for p in db_ckpt.get("pareto", [])
    ]

    return result, pareto


if __name__ == "__main__":
    main()
